### ISSUE TITLE
pip install fail on Python 3.6.0

### ISSUE THREAD

**Issue by vincent-paing** [Clarifai/clarifai-python#102]
It seems to be failing on  installing googleapis-common-protos

Here's the log
```
Running setup.py install for googleapis-common-protos ... error
    Complete output from command /Users/{redacted}/PythonProjects/MMRecipe/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/yp/3cn5m00s00g6h8n0b17ptq880000gn/T/pip-build-tpcv4ssi/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/yp/3cn5m00s00g6h8n0b17ptq880000gn/T/pip-_dxchejx-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/{redacted}/PythonProjects/MMRecipe/env/include/site/python3.6/googleapis-common-protos:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/Users/{redacted}/PythonProjects/MMRecipe/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
```

**Comment by vincent-paing** [comment]
It seems to be resolved when you run

```pip install --upgrade setuptools```
