### ISSUE TITLE
ModuleNotFoundError: No module named 'clarifai.rest'

### ISSUE THREAD

**Issue by FraTeG** [Clarifai/clarifai-python#131]
starting instapy with quickstart
================================
Traceback (most recent call last):
  File "C:\Users\franc\Downloads\instapy-quickstart-master\quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .clarifai_util import check_image
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Workflow
ModuleNotFoundError: No module named 'clarifai.rest'

**Comment by yangshengBE** [comment]
@FraTeG this lib has been deprecated. We highly suggest to use https://github.com/Clarifai/clarifai-python-grpc which has all the new features and better performance. If you still want to use this, you would need to install version 2.0.18 instead of latest version 9.1.2 which is built on top of clarifai-python-grpc.
