### ISSUE TITLE
I have issue with d 'clarifai.rest'

### ISSUE THREAD

**Issue by kristijorgji** [Clarifai/clarifai-python#132]
This import is failing
`
from clarifai.rest import ClarifaiApp, Image as ClImage
`
```
Traceback (most recent call last):
  File "/Users/kristi.jorgji/Downloads/app/quickstart.py", line 7, in <module>
    from module import module
  File "/Users/kristi.jorgji/Downloads/app/module/__init__.py", line 2, in <module>
    from .module import module
  File "/Users/kristi.jorgji/Downloads/app/module/module.py", line 23, in <module>
    from .clarifai_util import check_image
  File "/Users/kristi.jorgji/Downloads/app/module/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
ModuleNotFoundError: No module named 'clarifai.rest'

```

**Comment by excaliburne** [comment]
Hey, we don't support this package anymore, please switch to https://github.com/Clarifai/clarifai-python-grpc if possible.
