### ISSUE TITLE
 Message type "clarifai.api.ModelVersion" has no field named "train_stats"

### ISSUE THREAD

**Issue by syalanuj** [Clarifai/clarifai-python#95]
While creating an instance of Clarifai Object, I get the following stack trace

`Traceback (most recent call last):
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 489, in _ConvertFieldValuePair
    message_descriptor.fields))
google.protobuf.json_format.ParseError: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 547, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 29, in _ConvertFieldValuePair
    super(_CustomParser, self)._ConvertFieldValuePair(js, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 554, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 532, in _ConvertFieldValuePair
    self.ConvertMessage(item, sub_message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 29, in _ConvertFieldValuePair
    super(_CustomParser, self)._ConvertFieldValuePair(js, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 552, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse model_version field: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/application.py", line 3, in <module>
    from tag_watch import app,api
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/tag_watch/__init__.py", line 57, in <module>
    clarifaiService = ClarifaiService()
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/tag_watch/services/clarifai_service.py", line 9, in __init__
    app = ClarifaiApp(api_key=config.CLARIFAI_KEY)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 115, in __init__
    self.models = Models(self.api)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 1053, in __init__
    self.model_id_cache = self.init_model_cache()
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 1070, in init_model_cache
    for m in models:
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 1173, in get_all
    res = self.api.get_models(page, per_page)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 3754, in get_models
    ListModelsRequest(page=page, per_page=per_page))
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/client.py", line 3463, in _grpc_request
    res = method(argument)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/grpc/grpc_json_channel.py", line 194, in __call__
    result = dict_to_protobuf(message, response_json)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 9, in dict_to_protobuf
    parser.ConvertMessage(js_dict, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 29, in _ConvertFieldValuePair
    super(_CustomParser, self)._ConvertFieldValuePair(js, message)
  File "/Users/anuj/Desktop/AnujSyal/projects/repo/tag-watch/server/env/lib/python3.6/site-packages/google/protobuf/json_format.py", line 552, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse models field: Failed to parse model_version field: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): <MessageFields sequence>`

**Comment by rok-povsic** [comment]
@syalanuj Hello, we are aware of this issue. Please upgrade to the latest version 2.4.1 which fixes it.

**Comment by syalanuj** [comment]
@rok-povsic Thanks a lot, its working now
